- name: Install GnuPG
  apt:
    name: gnupg
    state: present

- name: Add AdoptOpenJDK's signing key
  apt_key:
    id: 8ED17AF5D7E675EB3EE3BCE98AC3B29174885C03
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public

- name: Install AdoptOpenJDK repository
  apt_repository:
    repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
    mode: 0644
    state: present

- name: Install OpenJDK 8 LTS
  apt:
    name: adoptopenjdk-8-hotspot
    state: present
