- import_tasks: java.yml
  tags: java

- name: Create Minecraft user
  user:
    name: "{{ minecraft_user }}"
    home: "{{ minecraft_dir }}"
    skeleton: /etc/skel
    shell: /bin/bash

- name: Create Minecraft directories
  file:
    path: "{{ item }}"
    owner: "{{ minecraft_user }}"
    state: directory
  loop:
    - "{{ minecraft_jars }}"
    - "{{ minecraft_root }}"

- name: Download Minecraft server
  get_url:
    url: "{{ minecraft_url }}"
    dest: "{{ minecraft_server }}"
    checksum: "sha1:{{ minecraft_sha1 }}"
    owner: "{{ minecraft_user }}"
    mode: 0600

- name: Link Minecraft server jar
  file:
    src: "{{ minecraft_server }}"
    dest: "{{ minecraft_root }}/server.jar"
    owner: "{{ minecraft_user }}"
    state: link

- name: Deploy Minecraft start script
  template:
    src: start.sh.j2
    dest: "{{ minecraft_root }}/start.sh"
    owner: "{{ minecraft_user }}"
    mode: 0700

- name: Deploy Minecraft service
  template:
    src: minecraft.service.j2
    dest: "/etc/systemd/system/minecraft.service"
    mode: 0600

- name: Agree to Mojang's EULA
  template:
    src: eula.txt.j2
    dest: "{{ minecraft_root }}/eula.txt"
    owner: "{{ minecraft_user }}"
    mode: 0600

- name: Start Minecraft service
  service:
    name: minecraft
    state: started
